// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmZk3PzF8ybWtUbRhpGpSXmMPfErlOCBI',
    appId: '1:510991387756:web:87ad25b6d8da4a813a5c49',
    messagingSenderId: '510991387756',
    projectId: 'solar-crm-f07a9',
    authDomain: 'solar-crm-f07a9.firebaseapp.com',
    storageBucket: 'solar-crm-f07a9.firebasestorage.app',
    measurementId: 'G-5B2SM5ZD66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmkXIH_60adu3SXZKSySBuU05-PDNLIjE',
    appId: '1:510991387756:android:e51a896fa0a444333a5c49',
    messagingSenderId: '510991387756',
    projectId: 'solar-crm-f07a9',
    storageBucket: 'solar-crm-f07a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt_OVmfW8zV_uMun89i2ui93vr4DrJZHY',
    appId: '1:510991387756:ios:9e87cded47abce7f3a5c49',
    messagingSenderId: '510991387756',
    projectId: 'solar-crm-f07a9',
    storageBucket: 'solar-crm-f07a9.firebasestorage.app',
    iosBundleId: 'com.example.solarProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt_OVmfW8zV_uMun89i2ui93vr4DrJZHY',
    appId: '1:510991387756:ios:9e87cded47abce7f3a5c49',
    messagingSenderId: '510991387756',
    projectId: 'solar-crm-f07a9',
    storageBucket: 'solar-crm-f07a9.firebasestorage.app',
    iosBundleId: 'com.example.solarProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmZk3PzF8ybWtUbRhpGpSXmMPfErlOCBI',
    appId: '1:510991387756:web:f384348150d709ac3a5c49',
    messagingSenderId: '510991387756',
    projectId: 'solar-crm-f07a9',
    authDomain: 'solar-crm-f07a9.firebaseapp.com',
    storageBucket: 'solar-crm-f07a9.firebasestorage.app',
    measurementId: 'G-3M96PT726R',
  );
}
