import 'package:flutter/material.dart';

class AppColors {
  AppColors._();

  static const Color primary       = Color(0xFF5B4FCF);   
  static const Color primaryDark   = Color(0xFF4A3EBF);  
  static const Color primaryLight  = Color(0xFF7B6FE0); 
  static const Color primaryTint   = Color(0xFFEDE9FC); 

  // ── Purple Scale (light → dark) ──────────────────────────────────────────
  static const Color purple50      = Color(0xFFF8F7FF);  
  static const Color purple100     = Color(0xFFEDE9FC);  
  static const Color purple200     = Color(0xFFD5CFFA); 
  static const Color purple300     = Color(0xFFB8AFF5); 
  static const Color purple400     = Color(0xFF8F84E8);  
  static const Color purple500     = Color(0xFF5B4FCF);  
  static const Color purple600     = Color(0xFF4A3EBF); 
  static const Color purple700     = Color(0xFF3B30A8); 
  static const Color purple800     = Color(0xFF2C2380); // very dark
  static const Color purple900     = Color(0xFF1E1859); // near-black purple (darkNavy)

  // ── Aliases used across the app ──────────────────────────────────────────
  static const Color solar             = primary;
  static const Color solarLight        = purple100;
  static const Color darkNavy          = purple900;
  static const Color background        = purple50;
  static const Color surface           = Color(0xFFFFFFFF);
  static const Color indigo            = primary;
  static const Color indigo50          = purple100;
  static const Color indigo500         = primary;
  static const Color indigo600         = primaryDark;
  static const Color indigoLight       = purple200;
  static const Color indigoVariant1    = purple400;
  static const Color indigoVariant2    = purple400;
  static const Color indigoVariant3    = purple400;
  static const Color indigoVariant4    = purple400;
  static const Color violet50          = purple50;
  static const Color violet100         = purple100;
  static const Color violet600         = primary;
  static const Color blue              = primaryLight;
  static const Color blueLight         = purple100;
  static const Color blueAccent        = primary;
  static const Color blueDark          = primaryDark;
  static const Color blue50            = purple50;
  static const Color blue100           = purple100;
  static const Color blue600           = primaryDark;
  static const Color blue700           = purple700;
  static const Color blueCustom        = primary;
  static const Color blueVariant       = primaryLight;
  static const Color blueLight2        = purple300;
  static const Color lightBlue1        = purple50;
  static const Color lightBlue2        = purple100;
  static const Color lightBlue3        = purple100;
  static const Color lightBlue4        = purple100;
  static const Color lightBlue5        = purple100;
  static const Color lightBlue6        = purple50;
  static const Color cyan              = primaryLight;
  static const Color cyan600           = primaryDark;
  static const Color cyanLight         = purple100;
  static const Color teal              = primary;
  static const Color tealLight         = purple100;
  static const Color tealAccent        = primaryLight;
  static const Color tealDark          = primaryDark;
  static const Color purple            = primary;
  static const Color purpleLight       = purple100;
  static const Color purpleDark        = primaryDark;
  static const Color purple1           = primaryDark;
  static const Color purpleVariant1    = primaryLight;
  static const Color purpleVariant2    = primaryLight;
  static const Color purpleVariant3    = purple300;
  static const Color purpleVariant4    = purple300;
  static const Color purpleVariant5    = purple300;
  static const Color purpleVariant6    = purple300;
  static const Color purpleAccent      = purple100;
  static const Color purpleLight1      = purple100;
  static const Color purpleLight2      = purple200;
  static const Color purpleLight3      = purple100;
  static const Color purpleLight4      = purple100;
  static const Color purpleLight5      = purple100;

  // ── Status Colors ────────────────────────────────────────────────────────
  static const Color success           = primaryLight;
  static const Color successLight      = purple100;
  static const Color successGreen      = primaryLight;
  static const Color error             = purple700;   // deep purple for errors
  static const Color errorLight        = purple100;
  static const Color warning           = primaryLight;
  static const Color green             = primaryLight;
  static const Color greenSuccess      = primaryLight;
  static const Color greenLight        = purple100;
  static const Color greenDark         = primaryDark;
  static const Color greenAccent       = primaryLight;
  static const Color greenAccent2      = purple200;
  static const Color greenDarker       = purple700;
  static const Color greenLight1       = purple200;
  static const Color greenLight2       = primaryLight;
  static const Color green600          = primaryDark;
  static const Color green700          = purple700;
  static const Color green800          = purple700;
  static const Color green900          = primaryDark;
  static const Color greenSuccess2     = primary;
  static const Color redError          = purple700;
  static const Color amber             = primaryLight;
  static const Color amberLight        = purple100;
  static const Color amberdark         = primaryDark;
  static const Color orange            = primaryLight;
  static const Color orange2           = primaryLight;
  static const Color orange3           = primary;
  static const Color orange4           = primaryLight;
  static const Color orange5           = primaryLight;
  static const Color orange6           = primary;
  static const Color orange600         = primaryDark;
  static const Color orange700         = primaryDark;
  static const Color orange800         = purple700;
  static const Color orange900         = primaryDark;
  static const Color orangeAccent      = primaryLight;
  static const Color orangeAccent2     = primaryLight;
  static const Color orangeAccent3     = primaryLight;
  static const Color yellow            = primaryLight;
  static const Color yellowLight       = purple100;
  static const Color yellowAccent      = purple100;
  static const Color pink              = primaryLight;
  static const Color pinkLight         = purple100;
  static const Color pink500           = primaryLight;
  static const Color pinkAccent        = purple200;
  static const Color pinkLight1        = purple100;
  static const Color pinkLight2        = purple100;
  static const Color pinkLight3        = purple100;
  static const Color pinkLight4        = purple200;
  static const Color red               = purple700;
  static const Color red700            = primaryDark;
  static const Color redDark           = purple800;
  static const Color redDarker         = purple700;
  static const Color redVariant1       = primary;
  static const Color redVariant2       = primaryLight;
  static const Color redVariant3       = primaryLight;
  static const Color redVariant4       = purple400;
  static const Color redVariant5       = purple400;
  static const Color redVariant6       = primary;
  static const Color redVariant7       = primary;
  static const Color redVariant8       = primaryLight;

  // ── Text Colors ──────────────────────────────────────────────────────────
  static const Color textDark          = Color(0xFF1E1859); // purple900
  static const Color textGray          = Color(0xFF6B6A8A); // purple-tinted mid
  static const Color textLight         = Color(0xFFABA8CC); // hint text
  static const Color divider           = purple200;

  // ── Slate Scale (purple-tinted grays) ────────────────────────────────────
  static const Color slate50           = Color(0xFFF8F7FF);
  static const Color slate100          = Color(0xFFEDE9FC);
  static const Color slate200          = purple200;
  static const Color slate300          = purple300;
  static const Color slate400          = purple400;
  static const Color slate500          = Color(0xFF6B6A8A);
  static const Color slate600          = Color(0xFF4A4870);
  static const Color slate700          = Color(0xFF35335A);
  static const Color slate800          = Color(0xFF26244A);
  static const Color slate900          = purple900;

  // ── Gray Scale (very slightly purple-tinted neutrals) ────────────────────
  static const Color gray50            = Color(0xFFF8F8FB);
  static const Color gray100           = Color(0xFFF1F0FA);
  static const Color gray200           = Color(0xFFE2E0F0);
  static const Color gray300           = Color(0xFFCECCE4);
  static const Color gray400           = Color(0xFF6B6A8A);
  static const Color gray500           = Color(0xFF6B6A8A);
  static const Color gray600           = Color(0xFF4A4870);
  static const Color grayDark          = Color(0xFF2C2B4A);
  static const Color grayDark2         = Color(0xFF2C2B4A);
  static const Color grayDark3         = Color(0xFF1A1838);
  static const Color grayMedium        = Color(0xFF4A4870);
  static const Color grayMedium2       = Color(0xFF2C2B4A);
  static const Color grayLight         = Color(0xFFABA8CC);
  static const Color grayLight2        = Color(0xFFB8B6D4);
  static const Color grayLight3        = Color(0xFFD5D3E8);
  static const Color grayCustom        = Color(0xFFCBC8DF);
  static const Color gray200Custom     = purple200;
  static const Color gray300Custom     = purple300;
  static const Color gray400Custom     = purple300;
  static const Color gray500Custom     = Color(0xFFABA8CC);
  static const Color gray600Custom     = Color(0xFF8A88AA);
  static const Color gray700Custom     = Color(0xFF4A4870);
  static const Color gray800Custom     = Color(0xFF2C2B4A);

  // ── Light Backgrounds ────────────────────────────────────────────────────
  static const Color lightBg           = purple50;
  static const Color lightBg2          = purple50;
  static const Color lightBg3          = purple100;
  static const Color lightBg4          = purple100;
  static const Color lightBg5          = purple100;
  static const Color lightBg6          = purple100;
  static const Color lightPurple1      = purple100;
  static const Color lightPurple2      = purple50;
  static const Color lightPurple3      = purple100;
  static const Color lightPurple4      = purple100;
  static const Color lightPurple5      = purple100;
  static const Color veryLight1        = purple50;
  static const Color veryLight2        = purple50;
  static const Color veryLight3        = purple50;   // page scaffold background
  static const Color veryLight4        = purple100;
  static const Color veryLight5        = purple100;
  static const Color veryLight6        = purple50;
  static const Color veryLight7        = Color(0xFFFFFFFF);
  static const Color veryLight8        = purple100;
  static const Color veryLight9        = purple50;
  static const Color veryLight10       = purple50;
  static const Color bgDark            = purple800;
  static const Color bgLight1          = purple100;
  static const Color bgLight2          = purple100;
  static const Color bgLight3          = purple50;
  static const Color bgLight4          = purple200;
  static const Color bgLight5          = purple100;
  static const Color bgLight6          = Color(0xFFFFFFFF);
  static const Color bgLight7          = purple50;
  static const Color bgLight8          = purple50;
  static const Color bgLight9          = purple50;
  static const Color bgLight10         = purple50;
  static const Color bgLight11         = purple50;
  static const Color bgLight12         = Color(0xFFFFFFFF);
  static const Color bgOther1          = purple50;
  static const Color bgOther2          = purple100;
  static const Color bgOther3          = purple100;
  static const Color bgOther4          = purple100;
  static const Color bgOther5          = purple100;
  static const Color bgOther6          = purple200;
  static const Color accentDarkGreen   = purple800;
  static const Color accentDarkOrange  = purple50;
  static const Color accentOrange      = purple100;
  static const Color other1            = purple100;
  static const Color other2            = purple50;
  static const Color other3            = purple50;
  static const Color other4            = purple50;
  static const Color other5            = purple100;
  static const Color other6            = purple50;
}